spring.application.name=aprende-shop
#aprendeshopdb es el nombre que le damos a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/aprendeshopdb
spring.datasource.username=root
spring.datasource.password=Pa$$w0rd

#create create-drop update validate
spring.jpa.hibernate.ddl-auto=validate
