-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 13:27:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aprendeshopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aprendeshopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aprendeshopdb` DEFAULT CHARACTER SET utf8 ;
USE `aprendeshopdb` ;

-- -----------------------------------------------------
-- Table `aprendeshopdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendeshopdb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `usuariocol` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(2) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aprendeshopdb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendeshopdb`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombreCurso` VARCHAR(45) NOT NULL,
  `descripcionCorta` VARCHAR(200) NOT NULL,
  `descripcionDetallada` VARCHAR(500) NOT NULL,
  `categoria` VARCHAR(20) NOT NULL,
  `nivelDificultad` VARCHAR(15) NOT NULL,
  `duracionTotal` INT NOT NULL,
  `idioma` VARCHAR(2) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `valoracionInicial` INT NOT NULL,
  `imagenPrincipal` VARCHAR(100) NOT NULL,
  `materiales` VARCHAR(200) NOT NULL,
  `galeriaAdicional` VARCHAR(200) NOT NULL,
  `incluyeKit` TINYINT NOT NULL,
  `descripcionKit` VARCHAR(200) NULL,
  `estado` TINYINT NOT NULL,
  `precioKit` DOUBLE NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aprendeshopdb`.`comprausuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendeshopdb`.`comprausuario` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUsuario` INT NOT NULL,
  `curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_comprausuario_usuario_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_comprausuario_curso1_idx` (`curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_comprausuario_usuario`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `aprendeshopdb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprausuario_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `aprendeshopdb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aprendeshopdb`.`resena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendeshopdb`.`resena` (
  `idResena` INT NOT NULL AUTO_INCREMENT,
  `calificacion` INT NOT NULL,
  `cometarios` VARCHAR(250) NOT NULL,
  `resena` VARCHAR(250) NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  `curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idResena`),
  INDEX `fk_resena_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_resena_curso1_idx` (`curso_idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_resena_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `aprendeshopdb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resena_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `aprendeshopdb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
